### ISSUE TITLE
Client Crash when hovering over a setting from AIOT inside Configured Mod

### ISSUE THREAD

**Issue by ghost** [ChaoticTrials/VanillaAIOTs#1]
### Minecraft version

1.18.2

### Vanilla AIOTs version

1.18.2-1.1.1

### Forge version

1.18.2-40.1.19

### The latest.log file

https://gist.github.com/ObiGanovi/2d58506acb170175f3d9d95fb2194952

### Issue description

 Client Crash when hovering over a setting from AIOT inside Configured Mod

### Steps to reproduce

1. Startmenu
2. click Mods (Configured installed)
3. search for AIOT
4. click "configure" on the right
5. hover with the mouse over a setting

### Other information

Crashreport:
https://gist.github.com/ObiGanovi/e3b1e492e77dceb8af1b7fcdf7b991d4

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/170287595-41effb38-23fa-4be2-afd7-b03d2b0d7bb1.png)
Sorry, but I don't see the button `configure` on the right. I only see the `Config` button on the left. I did install `Configured` (as you can see in the screenshot). 
Sorry, I can't reproduce this issue. 
In your crash report, I also can see that the cause is by `com.jiggo.editenchanting.client.handler.TooltipHandler.onGatherComponents(TooltipHandler.java:74)`. I searched for `editenchanting` but wasn't able to find the mod.
